// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7lDIPwSW9p2c_eChP31O2M1ruIxfgJ3M',
    appId: '1:838570251672:web:99ab3ca3b15083dfc347ed',
    messagingSenderId: '838570251672',
    projectId: 'role-based-login-488b2',
    authDomain: 'role-based-login-488b2.firebaseapp.com',
    storageBucket: 'role-based-login-488b2.firebasestorage.app',
    measurementId: 'G-5GZWLR19SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTHZS1a1dO0EBT0-6viVHWr2bwpn8mnk',
    appId: '1:838570251672:android:1a47504ab4f085c8c347ed',
    messagingSenderId: '838570251672',
    projectId: 'role-based-login-488b2',
    storageBucket: 'role-based-login-488b2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6xH9SyiF5jy0rR4uNuTdY4zCwMJ4R57s',
    appId: '1:838570251672:ios:434e6eb001c13d7bc347ed',
    messagingSenderId: '838570251672',
    projectId: 'role-based-login-488b2',
    storageBucket: 'role-based-login-488b2.firebasestorage.app',
    iosBundleId: 'com.example.myloginapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6xH9SyiF5jy0rR4uNuTdY4zCwMJ4R57s',
    appId: '1:838570251672:ios:434e6eb001c13d7bc347ed',
    messagingSenderId: '838570251672',
    projectId: 'role-based-login-488b2',
    storageBucket: 'role-based-login-488b2.firebasestorage.app',
    iosBundleId: 'com.example.myloginapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7lDIPwSW9p2c_eChP31O2M1ruIxfgJ3M',
    appId: '1:838570251672:web:f391b60531bef171c347ed',
    messagingSenderId: '838570251672',
    projectId: 'role-based-login-488b2',
    authDomain: 'role-based-login-488b2.firebaseapp.com',
    storageBucket: 'role-based-login-488b2.firebasestorage.app',
    measurementId: 'G-ZPRT8CK5QK',
  );

}